import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { runDockerEnv, type DockerEnvDeps } from './docker-env.js';
import { GENERATED_ENV_HEADER } from '../lib/docker/index.js';
import type { ProjectConfig } from '../lib/index.js';

let dir: string;

beforeEach(() => {
  dir = mkdtempSync(join(tmpdir(), 'crew-docker-env-'));
});

afterEach(() => {
  rmSync(dir, { recursive: true, force: true });
});

function makeConfig(overrides: Partial<ProjectConfig> = {}): ProjectConfig {
  return {
    name: 'recipes-app',
    repo_path: join(dir, 'Recipes-App'),
    default_branch: 'main',
    jira: { project_key: 'KAN', site: 'https://example.atlassian.net', ready_status: 'Ready for Development' },
    github: { repo: 'u/r' },
    docker: {
      canonical_worktree: 'Recipes-App',
      http_port_base: 8000,
      https_port_base: 8400,
      postgres_port_base: 15400,
      caddy_service: 'caddy',
      postgres_service: 'postgres',
    },
    db_clone: {
      postgres_service: 'postgres',
      postgres_user: 'postgres',
      postgres_database: 'postgres',
      required_tables: [],
      exclude_tables: ['kysely_migration*'],
    },
    ...overrides,
  };
}

function makeDeps(overrides: Partial<DockerEnvDeps> = {}): DockerEnvDeps & { logs: string[] } {
  const logs: string[] = [];
  return {
    cwd: dir,
    config: makeConfig(),
    log: (m) => logs.push(m),
    logs,
    ...overrides,
  };
}

describe('runDockerEnv', () => {
  it('writes a generated .env in the resolved worktree path and logs the summary', async () => {
    const worktree = join(dir, 'Recipes-App-KAN-23');
    mkdirSync(worktree);

    const deps = makeDeps({ cwd: worktree });
    const result = await runDockerEnv(undefined, deps);

    expect(result.ok).toBe(true);
    const content = readFileSync(join(worktree, '.env'), 'utf8');
    expect(content.startsWith(GENERATED_ENV_HEADER)).toBe(true);
    expect(content).toContain('COMPOSE_PROJECT_NAME=recipes-app-kan-23');
    // Each summary line shows up.
    const joined = deps.logs.join('\n');
    expect(joined).toContain('.env');
    expect(joined).toContain('project: recipes-app-kan-23');
  });

  it('honors a positional path argument for the target worktree', async () => {
    const worktree = join(dir, 'Recipes-App-KAN-23');
    mkdirSync(worktree);

    // cwd is somewhere else entirely.
    const deps = makeDeps({ cwd: dir });
    const result = await runDockerEnv(worktree, deps);

    expect(result.ok).toBe(true);
    expect(readFileSync(join(worktree, '.env'), 'utf8')).toContain(
      'COMPOSE_PROJECT_NAME=recipes-app-kan-23',
    );
  });

  it('uses canonical 80/443/5432 ports when path basename matches canonical_worktree', async () => {
    const worktree = join(dir, 'Recipes-App');
    mkdirSync(worktree);

    const result = await runDockerEnv(worktree, makeDeps());

    expect(result.ok).toBe(true);
    const content = readFileSync(join(worktree, '.env'), 'utf8');
    expect(content).toContain('CADDY_HTTP_PORT=80');
    expect(content).toContain('CADDY_HTTPS_PORT=443');
    expect(content).toContain('POSTGRES_PORT=5432');
  });

  it('refuses when the project config has no [docker] section', async () => {
    const worktree = join(dir, 'Recipes-App-KAN-23');
    mkdirSync(worktree);

    const deps = makeDeps({ cwd: worktree, config: makeConfig({ docker: undefined }) });
    const result = await runDockerEnv(undefined, deps);

    expect(result.ok).toBe(false);
    expect(result.reason).toMatch(/\[docker\]/);
  });

  it('refuses when the .env exists without the generated header', async () => {
    const worktree = join(dir, 'Recipes-App-KAN-23');
    mkdirSync(worktree);
    writeFileSync(join(worktree, '.env'), 'HAND_EDITED=1\n');

    const deps = makeDeps({ cwd: worktree });
    const result = await runDockerEnv(undefined, deps);

    expect(result.ok).toBe(false);
    expect(result.reason).toMatch(/not generated by crew/i);
    // Original file untouched.
    expect(readFileSync(join(worktree, '.env'), 'utf8')).toBe('HAND_EDITED=1\n');
  });

  it('refuses when the resolved path is not a directory', async () => {
    const result = await runDockerEnv(join(dir, 'missing'), makeDeps());
    expect(result.ok).toBe(false);
    expect(result.reason).toMatch(/not a directory/i);
  });
});
