import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { existsSync, readFileSync, writeFileSync, mkdirSync, mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { resolveExitCode, runCommand } from './run.js';

describe('runCommand', () => {
  it('is named "run"', () => {
    expect(runCommand.name()).toBe('run');
  });

  it('takes a single required <key> argument', () => {
    const args = runCommand.registeredArguments;
    expect(args).toHaveLength(1);
    expect(args[0]?.name()).toBe('key');
    expect(args[0]?.required).toBe(true);
  });

  it('exposes a --skip-docker option', () => {
    const opts = runCommand.options;
    const skip = opts.find((o) => o.long === '--skip-docker');
    expect(skip).toBeDefined();
  });

  it('exposes a -m / --message option', () => {
    const opts = runCommand.options;
    const message = opts.find((o) => o.long === '--message');
    expect(message).toBeDefined();
    expect(message?.short).toBe('-m');
  });

  it('has a non-empty description', () => {
    expect(runCommand.description().length).toBeGreaterThan(0);
  });
});

describe('resolveExitCode', () => {
  it('returns the natural exit code when the process exited normally', () => {
    expect(resolveExitCode({ exitCode: 0 }, false)).toBe(0);
    expect(resolveExitCode({ exitCode: 7 }, false)).toBe(7);
  });

  it('returns 130 when the user signaled an abort, regardless of exit code', () => {
    expect(resolveExitCode({ exitCode: 0 }, true)).toBe(130);
    expect(resolveExitCode({ exitCode: undefined, signal: 'SIGTERM' }, true)).toBe(130);
  });

  it('returns 130 when the child died from SIGINT/SIGTERM even without a local handler firing', () => {
    expect(resolveExitCode({ signal: 'SIGINT' }, false)).toBe(130);
    expect(resolveExitCode({ signal: 'SIGTERM' }, false)).toBe(130);
  });

  it('falls back to 1 when neither exit code nor signal is known', () => {
    expect(resolveExitCode({}, false)).toBe(1);
  });
});

describe('crew run + env.toml', () => {
  let dir: string;

  beforeEach(() => {
    dir = mkdtempSync(join(tmpdir(), 'crew-run-env-'));
  });

  afterEach(() => {
    rmSync(dir, { recursive: true, force: true });
  });

  it('uses the env-spec pipeline when env.toml exists at the canonical worktree root', async () => {
    const canonical = join(dir, 'fake-project');
    mkdirSync(canonical);
    writeFileSync(
      join(canonical, 'env.toml'),
      `
schema = 1
[orchestration]
COMPOSE_PROJECT_NAME = { kind = "template", value = "\${BASE_NAME}-\${WORKTREE_ID}" }
HTTP_PORT = { kind = "port", default = 80 }
[app]
SECRET = { source = "literal", value = "static" }
`,
    );

    const { bringUpWorktreeEnv } = await import('./run.js');
    const result = await bringUpWorktreeEnv({
      worktree: canonical,
      canonicalWorktreeName: 'fake-project',
      projectName: 'fake-project',
    });

    expect(result.kind).toBe('env-spec');
    expect(existsSync(join(canonical, '.env'))).toBe(true);
    expect(readFileSync(join(canonical, '.env'), 'utf8')).toMatch(/SECRET=static/);
  });

  it('falls back to writeDockerEnv when env.toml is absent', async () => {
    const canonical = join(dir, 'legacy-project');
    mkdirSync(canonical);

    const { bringUpWorktreeEnv } = await import('./run.js');
    const result = await bringUpWorktreeEnv({
      worktree: canonical,
      canonicalWorktreeName: 'legacy-project',
      projectName: 'legacy-project',
    });

    expect(result.kind).toBe('legacy');
    expect(readFileSync(join(canonical, '.env'), 'utf8')).toMatch(/^# Generated by crew/);
    expect(readFileSync(join(canonical, '.env'), 'utf8')).toMatch(/COMPOSE_PROJECT_NAME=/);
  });
});
