// Projects route — full page list + detail/edit + register.

function ProjectsList({ onOpen, onRegister }) {
  return (
    <div className="projects-page">
      <div className="projects-page__hd">
        <h1 className="page-title">Projects</h1>
        <button className="btn btn--accent" onClick={onRegister}>
          <Icon.Plus size={12} /> Register project
        </button>
      </div>
      <div className="projects-list">
        <div className="projects-list__hd">
          <div>Name</div>
          <div>Repo path</div>
          <div>Branch</div>
          <div>Jira</div>
          <div>Active</div>
          <div></div>
        </div>
        {MOCK_PROJECTS.map(p => (
          <div key={p.name} className="projects-list__row" onClick={() => onOpen(p.name)}>
            <div className="mono">{p.name}</div>
            <div className="mono dim">{p.repo_path}</div>
            <div className="mono">{p.default_branch}</div>
            <div className="mono">{p.jira_project_key}</div>
            <div className="mono">
              {p.activeRuns > 0
                ? <span className="badge-sm badge-sm--accent">{p.activeRuns}</span>
                : <span className="dim">—</span>}
            </div>
            <div className="dim"><Icon.Chevron dir="right" /></div>
          </div>
        ))}
      </div>
    </div>
  );
}

function ProjectDetail({ project, onBack, onRemove, onAgentOpen, onAgentAction, tweaks }) {
  const [editing, setEditing] = React.useState(false);
  const [confirmRm, setConfirmRm] = React.useState(false);
  const [form, setForm] = React.useState({ ...project });

  const toml = `# generated by crew
name = "${form.name}"
repo_path = "${form.repo_path}"
default_branch = "${form.default_branch}"
jira_project_key = "${form.jira_project_key}"
docker_compose = "${form.docker_compose}"
test_command = "${form.test_command}"`;

  return (
    <div className="projects-page">
      <div className="projects-page__hd">
        <div>
          <button className="btn btn--ghost btn--sm" onClick={onBack}>← Projects</button>
          <h1 className="page-title" style={{marginTop: 8}}>
            {project.name}
          </h1>
          <div className="dim mono" style={{fontSize: 12}}>~/.config/crew/projects/{project.name}.toml</div>
        </div>
        <div className="qa-group">
          {!editing
            ? <button className="btn" onClick={() => setEditing(true)}>Edit</button>
            : <>
                <button className="btn btn--ghost" onClick={() => { setEditing(false); setForm({ ...project }); }}>Cancel</button>
                <button className="btn btn--accent" onClick={() => setEditing(false)}>Save</button>
              </>}
          <button className="btn btn--danger" onClick={() => setConfirmRm(true)}>Remove</button>
        </div>
      </div>

      {!editing ? (
        <pre className="toml-view mono">{toml}</pre>
      ) : (
        <div className="form">
          {[
            ['name', 'Name'],
            ['repo_path', 'Repo path'],
            ['default_branch', 'Default branch'],
            ['jira_project_key', 'Jira project key'],
            ['docker_compose', 'Docker compose file'],
            ['test_command', 'Test command'],
          ].map(([k, lbl]) => (
            <label key={k} className="form__field">
              <span className="form__label">{lbl}</span>
              <input
                className="form__input mono"
                value={form[k]}
                onChange={e => setForm(f => ({ ...f, [k]: e.target.value }))}
              />
            </label>
          ))}
        </div>
      )}

      {confirmRm && (
        <div className="modal-scrim" onClick={() => setConfirmRm(false)}>
          <div className="modal modal--sm" onClick={e => e.stopPropagation()}>
            <div className="modal__body">
              <h2 className="modal__title">Remove <span className="mono">{project.name}</span>?</h2>
              <p className="dim" style={{marginTop: 8, lineHeight: 1.5}}>
                This deletes the registration TOML only. Your repo and worktrees are not touched.
              </p>
              <div className="modal__footer">
                <button className="btn btn--ghost" onClick={() => setConfirmRm(false)}>Cancel</button>
                <button className="btn btn--danger" onClick={() => { setConfirmRm(false); onRemove(); }}>Remove project</button>
              </div>
            </div>
          </div>
        </div>
      )}

      <div className="project-detail__agents">
        <h2 className="projects-page__sub-hd">Agents</h2>
        <AgentsList
          onOpen={onAgentOpen}
          onAction={onAgentAction}
          tweaks={tweaks}
          projectFilter={project.name}
        />
      </div>
    </div>
  );
}

function RegisterProjectModal({ onClose }) {
  const [form, setForm] = React.useState({
    name: '', repo_path: '~/code/', default_branch: 'main',
    jira_project_key: '', docker_compose: 'docker-compose.yml', test_command: '',
  });
  React.useEffect(() => {
    const onKey = (e) => { if (e.key === 'Escape') onClose(); };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [onClose]);
  return (
    <div className="modal-scrim" onClick={onClose}>
      <div className="modal" onClick={e => e.stopPropagation()}>
        <header className="modal__hd">
          <div className="modal__steps"><span className="modal__step on">Register a project</span></div>
          <button className="icon-btn" onClick={onClose}><Icon.Close /></button>
        </header>
        <div className="modal__body">
          <div className="form">
            {[
              ['name', 'Name', 'my-project'],
              ['repo_path', 'Repo path', '~/code/my-project'],
              ['default_branch', 'Default branch', 'main'],
              ['jira_project_key', 'Jira project key', 'PROJ'],
              ['docker_compose', 'Docker compose file', 'docker-compose.yml'],
              ['test_command', 'Test command', 'pnpm test'],
            ].map(([k, lbl, ph]) => (
              <label key={k} className="form__field">
                <span className="form__label">{lbl}</span>
                <input className="form__input mono" placeholder={ph} value={form[k]}
                  onChange={e => setForm(f => ({ ...f, [k]: e.target.value }))} />
              </label>
            ))}
          </div>
          <div className="modal__footer">
            <button className="btn btn--ghost" onClick={onClose}>Cancel</button>
            <button className="btn btn--accent" onClick={onClose}>Register</button>
          </div>
        </div>
      </div>
    </div>
  );
}

function ProjectsRoute({ subRoute, onNavigate, onAgentOpen, onAgentAction, tweaks }) {
  const [registering, setRegistering] = React.useState(false);

  if (subRoute && subRoute !== '') {
    const project = MOCK_PROJECTS.find(p => p.name === subRoute);
    if (project) return (
      <ProjectDetail
        project={project}
        onBack={() => onNavigate('/projects')}
        onRemove={() => onNavigate('/projects')}
        onAgentOpen={onAgentOpen}
        onAgentAction={onAgentAction}
        tweaks={tweaks}
      />
    );
  }

  return (
    <>
      <ProjectsList
        onOpen={(name) => onNavigate(`/projects/${name}`)}
        onRegister={() => setRegistering(true)}
      />
      {registering && <RegisterProjectModal onClose={() => setRegistering(false)} />}
    </>
  );
}

window.ProjectsRoute = ProjectsRoute;
