import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

export const GENERATED_ENV_HEADER =
  '# Generated by crew — re-run `crew env init` (canonical) or `crew env refresh` to regenerate.';

export interface EmitOptions {
  /** Worktree root directory. `.env` and `.env.<context>` files are written here. */
  worktreeRoot: string;
  /** Variables for the base .env. */
  base: Record<string, string>;
  /** Per-context override files. */
  contexts: Record<string, Record<string, string>>;
}

function refuseIfHandEdited(path: string): void {
  if (!existsSync(path)) return;
  const existing = readFileSync(path, 'utf8');
  if (!existing.startsWith(GENERATED_ENV_HEADER)) {
    throw new Error(
      `emit: ${path} exists and was not generated by crew. ` +
        `Move it aside (e.g. mv ${path} ${path}.bak) to regenerate.`,
    );
  }
}

function render(map: Record<string, string>): string {
  const keys = Object.keys(map).sort();
  return [GENERATED_ENV_HEADER, ...keys.map((k) => `${k}=${map[k]}`), ''].join('\n');
}

export function emit(opts: EmitOptions): void {
  const baseEnvPath = join(opts.worktreeRoot, '.env');
  refuseIfHandEdited(baseEnvPath);
  for (const ctxName of Object.keys(opts.contexts)) {
    refuseIfHandEdited(join(opts.worktreeRoot, `.env.${ctxName}`));
  }

  writeFileSync(baseEnvPath, render(opts.base));
  for (const [ctxName, vars] of Object.entries(opts.contexts)) {
    writeFileSync(join(opts.worktreeRoot, `.env.${ctxName}`), render(vars));
  }
}
