import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdtempSync, rmSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { emit, GENERATED_ENV_HEADER } from './emit.js';

let dir: string;

beforeEach(() => {
  dir = mkdtempSync(join(tmpdir(), 'crew-emit-'));
});

afterEach(() => {
  rmSync(dir, { recursive: true, force: true });
});

describe('emit', () => {
  it('writes .env with the generated header followed by sorted KEY=VALUE pairs', () => {
    emit({
      worktreeRoot: dir,
      base: { B_KEY: '2', A_KEY: '1' },
      contexts: {},
    });
    const content = readFileSync(join(dir, '.env'), 'utf8');
    expect(content.startsWith(GENERATED_ENV_HEADER)).toBe(true);
    expect(content.indexOf('A_KEY=1')).toBeLessThan(content.indexOf('B_KEY=2'));
  });

  it('writes one .env.<context> per context block', () => {
    emit({
      worktreeRoot: dir,
      base: { X: 'x' },
      contexts: { 'docker-backend': { Y: 'y' }, prod: { Z: 'z' } },
    });
    expect(readFileSync(join(dir, '.env.docker-backend'), 'utf8')).toContain('Y=y');
    expect(readFileSync(join(dir, '.env.prod'), 'utf8')).toContain('Z=z');
  });

  it('refuses to overwrite a .env without the generated header', () => {
    writeFileSync(join(dir, '.env'), 'HAND_EDITED=1\n');
    expect(() => emit({ worktreeRoot: dir, base: { X: 'x' }, contexts: {} })).toThrow(
      /not generated by crew/i,
    );
    expect(readFileSync(join(dir, '.env'), 'utf8')).toBe('HAND_EDITED=1\n');
  });

  it('overwrites a .env that has the generated header', () => {
    writeFileSync(join(dir, '.env'), `${GENERATED_ENV_HEADER}\nOLD=1\n`);
    emit({ worktreeRoot: dir, base: { NEW: 'new' }, contexts: {} });
    const content = readFileSync(join(dir, '.env'), 'utf8');
    expect(content).not.toContain('OLD=1');
    expect(content).toContain('NEW=new');
  });
});
