import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdtemp, rm, mkdir, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { resolveBaseURL } from './playwright.config.js';

describe('resolveBaseURL', () => {
  let repoRoot: string;
  let savedEnv: typeof process.env;

  beforeEach(async () => {
    repoRoot = await mkdtemp(path.join(tmpdir(), 'pw-config-'));
    await mkdir(path.join(repoRoot, '.git'));
    savedEnv = { ...process.env };
    delete process.env.PLAYWRIGHT_BASE_URL;
  });

  afterEach(async () => {
    await rm(repoRoot, { recursive: true, force: true });
    process.env = savedEnv;
  });

  it('returns PLAYWRIGHT_BASE_URL when set', () => {
    process.env.PLAYWRIGHT_BASE_URL = 'http://override:9999';
    expect(resolveBaseURL(repoRoot)).toBe('http://override:9999');
  });

  it('returns APP_URL from .env when PLAYWRIGHT_BASE_URL is unset', async () => {
    await writeFile(
      path.join(repoRoot, '.env'),
      '# Generated by crew\nAPP_URL=http://localhost:21559\nCREW_PORT=29066\n',
    );
    expect(resolveBaseURL(repoRoot)).toBe('http://localhost:21559');
  });

  it('throws a helpful error when .env is missing', () => {
    expect(() => resolveBaseURL(repoRoot)).toThrow(/\.env/);
    expect(() => resolveBaseURL(repoRoot)).toThrow(/crew env/);
  });

  it('throws a helpful error when .env has no APP_URL line', async () => {
    await writeFile(
      path.join(repoRoot, '.env'),
      'CREW_PORT=29066\nDAEMON_URL=http://localhost:29066\n',
    );
    expect(() => resolveBaseURL(repoRoot)).toThrow(/APP_URL/);
    expect(() => resolveBaseURL(repoRoot)).toThrow(/crew env refresh/);
  });
});
