import { describe, expect, it } from 'vitest';

import { jsonToToml } from './jsonToToml.js';

describe('jsonToToml', () => {
  it('formats flat string + number + boolean keys', () => {
    expect(jsonToToml({ name: 'a', count: 3, ok: true })).toBe('name = "a"\ncount = 3\nok = true');
  });

  it('formats arrays of primitives inline', () => {
    expect(jsonToToml({ tags: ['x', 'y'] })).toBe('tags = ["x", "y"]');
  });

  it('emits a [section] block for nested objects', () => {
    expect(jsonToToml({ name: 'a', jira: { project_key: 'KAN' } })).toBe(
      'name = "a"\n\n[jira]\nproject_key = "KAN"',
    );
  });

  it('escapes embedded double quotes in strings', () => {
    expect(jsonToToml({ note: 'has "quotes"' })).toBe('note = "has \\"quotes\\""');
  });

  it('preserves a leading comment when provided', () => {
    expect(jsonToToml({ name: 'a' }, { leadingComment: '# generated by crew' })).toBe(
      '# generated by crew\nname = "a"',
    );
  });

  it('emits sections in insertion order, scalars first', () => {
    const out = jsonToToml({
      name: 'kanban-api',
      jira: { project_key: 'KAN' },
      default_branch: 'main',
      github: { repo: 'example/kanban-api' },
    });
    expect(out).toBe(
      [
        'name = "kanban-api"',
        'default_branch = "main"',
        '',
        '[jira]',
        'project_key = "KAN"',
        '',
        '[github]',
        'repo = "example/kanban-api"',
      ].join('\n'),
    );
  });
});
