import { render, screen } from '@testing-library/react';
import { describe, expect, it } from 'vitest';

import { ProjectConfigBlock } from './ProjectConfigBlock.js';
import type { ProjectConfig } from '../data/types.js';

const SAMPLE: ProjectConfig = {
  name: 'kanban-api',
  repo_path: '~/code/kanban-api',
  default_branch: 'main',
  jira: { project_key: 'KAN', site: 'https://example.atlassian.net' },
  github: { repo: 'example/kanban-api' },
  db_clone: {
    postgres_service: 'postgres',
    postgres_user: 'postgres',
    postgres_database: 'postgres',
    required_tables: [],
    exclude_tables: ['kysely_migration*'],
  },
};

describe('ProjectConfigBlock', () => {
  it('renders the config as TOML inside a <pre>', () => {
    render(<ProjectConfigBlock config={SAMPLE} />);
    const pre = screen.getByTestId('project-config-toml');
    expect(pre.tagName).toBe('PRE');
    expect(pre.textContent).toMatch(/name = "kanban-api"/);
    expect(pre.textContent).toMatch(/\[jira\]/);
    expect(pre.textContent).toMatch(/project_key = "KAN"/);
  });

  it('includes a leading "generated by crew" comment', () => {
    render(<ProjectConfigBlock config={SAMPLE} />);
    expect(screen.getByTestId('project-config-toml').textContent).toMatch(/^# generated by crew/);
  });
});
