import { jsonToToml } from '../lib/jsonToToml.js';
import type { ProjectConfig } from '../data/types.js';

interface ProjectConfigBlockProps {
  config: ProjectConfig;
}

export function ProjectConfigBlock({ config }: ProjectConfigBlockProps) {
  const toml = jsonToToml(config as unknown as Parameters<typeof jsonToToml>[0], {
    leadingComment: '# generated by crew',
  });
  return (
    <div className="rounded-[14px] border border-white/10 bg-card p-6">
      <pre
        data-testid="project-config-toml"
        className="whitespace-pre font-mono text-sm text-muted-foreground"
      >
        {toml}
      </pre>
    </div>
  );
}
