import { existsSync, readFileSync, writeFileSync, statSync } from 'node:fs';
import { basename, join } from 'node:path';
import { portHash } from './port-hash.js';

export const GENERATED_ENV_HEADER =
  '# Generated by crew — re-run `crew run` or `crew docker-env` to regenerate.';

export interface WriteDockerEnvOptions {
  canonicalWorktree: string;
}

export interface WriteDockerEnvResult {
  envPath: string;
  composeProjectName: string;
  caddyHttpPort: number;
  caddyHttpsPort: number;
  postgresPort: number;
  appUrl: string;
}

/**
 * Generate a per-worktree docker `.env` for the given worktree directory.
 *
 * Mirrors the bash `scripts/docker-env.sh` from the Recipes-App era: the
 * canonical worktree keeps the standard ports (80/443/5432); other worktrees
 * get hash-derived ports in conflict-free ranges. Refuses to overwrite a
 * `.env` that lacks the generated header so hand-edited files are safe.
 */
export function writeDockerEnv(
  worktreePath: string,
  opts: WriteDockerEnvOptions,
): WriteDockerEnvResult {
  if (!existsSync(worktreePath) || !statSync(worktreePath).isDirectory()) {
    throw new Error(`writeDockerEnv: not a directory: ${worktreePath}`);
  }

  const envPath = join(worktreePath, '.env');
  if (existsSync(envPath)) {
    const existing = readFileSync(envPath, 'utf8');
    if (!existing.startsWith(GENERATED_ENV_HEADER)) {
      throw new Error(
        `writeDockerEnv: ${envPath} exists and was not generated by crew. ` +
          `Move it aside (e.g. mv ${envPath} ${envPath}.bak) to regenerate.`,
      );
    }
  }

  const worktreeBasename = basename(worktreePath);
  const isCanonical = worktreeBasename === opts.canonicalWorktree;

  const composeProjectName = worktreeBasename.toLowerCase();
  const ports = isCanonical ? { http: 80, https: 443, postgres: 5432 } : portHash(worktreeBasename);

  const appUrl = ports.https === 443 ? 'https://localhost' : `https://localhost:${ports.https}`;

  const content =
    `${GENERATED_ENV_HEADER}\n` +
    `COMPOSE_PROJECT_NAME=${composeProjectName}\n` +
    `CADDY_HTTP_PORT=${ports.http}\n` +
    `CADDY_HTTPS_PORT=${ports.https}\n` +
    `POSTGRES_PORT=${ports.postgres}\n` +
    `APP_URL=${appUrl}\n`;

  writeFileSync(envPath, content);

  return {
    envPath,
    composeProjectName,
    caddyHttpPort: ports.http,
    caddyHttpsPort: ports.https,
    postgresPort: ports.postgres,
    appUrl,
  };
}
