import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdtempSync, mkdirSync, rmSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { writeDockerEnv, GENERATED_ENV_HEADER } from './env.js';

let dir: string;

function makeWorktree(name: string): string {
  const worktree = join(dir, name);
  mkdirSync(worktree, { recursive: true });
  return worktree;
}

beforeEach(() => {
  dir = mkdtempSync(join(tmpdir(), 'crew-env-'));
});

afterEach(() => {
  rmSync(dir, { recursive: true, force: true });
});

describe('writeDockerEnv', () => {
  it('writes a generated .env with hash-derived ports for non-canonical worktrees', () => {
    const worktree = makeWorktree('Recipes-App-KAN-23');
    const result = writeDockerEnv(worktree, { canonicalWorktree: 'Recipes-App' });

    const content = readFileSync(join(worktree, '.env'), 'utf8');
    expect(content.startsWith(GENERATED_ENV_HEADER)).toBe(true);
    expect(content).toContain('COMPOSE_PROJECT_NAME=recipes-app-kan-23');
    expect(content).toContain('CADDY_HTTP_PORT=8021');
    expect(content).toContain('CADDY_HTTPS_PORT=8421');
    expect(content).toContain('POSTGRES_PORT=15421');
    expect(content).toContain('APP_URL=https://localhost:8421');

    expect(result).toEqual({
      composeProjectName: 'recipes-app-kan-23',
      caddyHttpPort: 8021,
      caddyHttpsPort: 8421,
      postgresPort: 15421,
      appUrl: 'https://localhost:8421',
      envPath: join(worktree, '.env'),
    });
  });

  it('uses canonical 80/443/5432 ports when worktree basename matches canonicalWorktree', () => {
    const worktree = makeWorktree('Recipes-App');
    writeDockerEnv(worktree, { canonicalWorktree: 'Recipes-App' });

    const content = readFileSync(join(worktree, '.env'), 'utf8');
    expect(content).toContain('COMPOSE_PROJECT_NAME=recipes-app');
    expect(content).toContain('CADDY_HTTP_PORT=80');
    expect(content).toContain('CADDY_HTTPS_PORT=443');
    expect(content).toContain('POSTGRES_PORT=5432');
    expect(content).toContain('APP_URL=https://localhost');
  });

  it('refuses to clobber a .env that lacks the generated header', () => {
    const worktree = makeWorktree('Recipes-App-KAN-9');
    writeFileSync(join(worktree, '.env'), 'HAND_EDITED=1\n', { flag: 'w' });

    expect(() => writeDockerEnv(worktree, { canonicalWorktree: 'Recipes-App' })).toThrow(
      /not generated by crew/i,
    );
    expect(readFileSync(join(worktree, '.env'), 'utf8')).toBe('HAND_EDITED=1\n');
  });

  it('overwrites an existing .env that has the generated header', () => {
    const worktree = makeWorktree('Recipes-App-KAN-9');
    writeFileSync(join(worktree, '.env'), `${GENERATED_ENV_HEADER}\nOLD=1\n`, { flag: 'w' });

    writeDockerEnv(worktree, { canonicalWorktree: 'Recipes-App' });
    const content = readFileSync(join(worktree, '.env'), 'utf8');
    expect(content).not.toContain('OLD=1');
    expect(content).toContain('COMPOSE_PROJECT_NAME=');
  });

  it('throws when the worktree directory does not exist', () => {
    expect(() =>
      writeDockerEnv(join(dir, 'missing'), { canonicalWorktree: 'Recipes-App' }),
    ).toThrow(/not a directory/i);
  });

  it('does not create the .env when validation fails', () => {
    const worktree = makeWorktree('Recipes-App-KAN-9');
    writeFileSync(join(worktree, '.env'), 'HAND_EDITED=1\n');

    expect(() => writeDockerEnv(worktree, { canonicalWorktree: 'Recipes-App' })).toThrow();
    expect(existsSync(join(worktree, '.env'))).toBe(true);
    expect(readFileSync(join(worktree, '.env'), 'utf8')).toBe('HAND_EDITED=1\n');
  });
});
